[package]
name = "may-clack"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"

[dependencies]
console = "0.15.7"
crossterm = "0.26.1"
is-unicode-supported = "0.1.0"
lazy_static = "1.4.0"
rustyline = "12.0.0"
thiserror = "1.0.44"
